version: "3.8"
services:
  redis:
    container_name: redis
    image: "redis:6.0.9"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/data
  timescaledb:
      image: "timescale/timescaledb:2.0.0-pg12"
      container_name: timescaledb
      ports:
        - "5432:5432"
      expose:
        - "5432"
      environment:
        POSTGRES_DB: "youbei-api"
        POSTGRES_USER: "youbei"
        POSTGRES_PASSWORD: "youbei"
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
        - timescale_data:/var/lib/postgresql
volumes:
  redis-data:
  timescale_data: