version: "3.8"
services:
  timescaledb:
      image: "timescale/timescaledb:2.0.0-pg12"
      container_name: timescaledb
      ports:
        - "5432:5432"
      expose:
        - "5432"
      environment:
        POSTGRES_DB: "youbei-api"
        POSTGRES_USER: "youbei"
        POSTGRES_PASSWORD: "youbei"
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
        - timescale_data:/var/lib/postgresql
volumes:
  timescale_data: