[ConnectorApi]
    Port = "5000"
    Username = ""
    Password = ""
    Addresses = [
        "erd1qqqqqqqqqqqqqpgqj8vnqw76wq333qwx2wjf2nyn89dc8jhct9usvxzd7g",
    ]
    Identifiers = [
        "put_nft_for_sale",
        "buy_nft",
        "withdraw_nft",
    ]

[Blockchain]
    ChainID = "D"
    GasPrice = 1_000_000_000
    PemPath = "./config/owner.pem"
    ProxyUrl = "https://devnet-gateway.elrond.com"
    MarketplaceAddress = "erd1qqqqqqqqqqqqqpgqj8vnqw76wq333qwx2wjf2nyn89dc8jhct9usvxzd7g"
    ListNftGasLimit = 20_000_000
    BuyNftGasLimit = 15_000_000
    WithdrawNftGasLimit = 15_000_000

[Database]
    Dialect = "postgres"
    Host = "localhost"
    Port = 5432
    DbName = "erdsea_db"
    User = "postgres"
    Password = "root"
    SslMode = "disable"
    MaxOpenConns = 50
    MaxIdleConns = 10
    ShouldMigrate = true

[Auth]
    JwtSecret = "jwtSecret"
    JwtIssuer = "localhost:5000"
    JwtKeySeedHex = "seed_in_hex_32_bytes"
    JwtExpiryMins = 15

[Cache]
    Url = "redis://localhost:6379"

[Swagger]
    Enabled = true
