[ConnectorApi]
    Port = "5000"

    Username = ""

    Password = ""

    Addresses = [
        "erd1qqqqqqqqqqqqqpgq3k89y42xjk2z05zu5vtjkcgsvhvjhu6nt9usruf2td",
    ]

    Identifiers = [
        "collection_register",
        "put_nft_for_sale",
        "buy_nft",
        "withdraw_nft",
    ]

[Blockchain]
    ChainID = "D"
    GasPrice = 1_000_000_000
    PemPath = "./config/owner.pem"
    ProxyUrl = "https://devnet-gateway.elrond.com"

[Database]
    Dialect = "postgres"
    Host = "localhost"
    Port = 5432
    DbName = "erdsea_db"
    User = "postgres"
    Password = "root"
    SslMode = "disable"
    MaxOpenConns = 50
    MaxIdleConns = 10
    ShouldMigrate = true

[Auth]
    JwtSecret = "bitcoin-to-1-milly"
    JwtIssuer = "localhost:5000"
    JwtKeySeedHex = "d6592724167553acf9c8cba9a7dbc7f514efc757d7906546cecfdfc5d4c2e8d1"
    JwtExpiryMins = 15

