[ConnectorApi]
    Address = "0.0.0.0:8080"
    Username = ""
    Password = ""
    Addresses = [
        "erd1qqqqqqqqqqqqqpgqhz4g5t6n7qkdupykngtp69ynw7ghcccry4wsx6423a",
    ]
    Identifiers = [
        "putNftForSale",
        "buyNft",
        "withdrawNft",
        "makeOffer",
        "acceptOffer",
        "cancelOffer",
        "startAuction",
        "placeBid",
        "endAuction",
        "deposit",
        "withdraw",
    ]

[Blockchain]
    ChainID = "D"
    GasPrice = 1_000_000_000
    PemPath = "config/dev-wallet-owner.pem"
    ProxyUrl = "https://testnet-gateway.elrond.com"
    MarketplaceAddress = "erd1qqqqqqqqqqqqqpgqhz4g5t6n7qkdupykngtp69ynw7ghcccry4wsx6423a"
    DeployerAddress = "erd1hh7gte28hahk9htwlhzf3gretusckhrqf4y6xv5p9qwznhn7y4wswnzua3"
    SystemSCAddress = "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u"
    ListNftGasLimit = 20_000_000
    BuyNftGasLimit = 15_000_000
    WithdrawNftGasLimit = 15_000_000
    MintTokenGasLimit = 25_000_000
    MakeOfferGasLimit = 20_000_000
    AcceptOfferGasLimit = 20_000_000
    CancelOfferGasLimit = 20_000_000
    StartAuctionGasLimit = 20_000_000
    PlaceBidGasLimit = 20_000_000
    EndAuctionGasLimit = 20_000_000
    DepositGasLimit = 10_000_000
    WithdrawGasLimit = 10_000_000
    WithdrawCreatorRoyaltiesGasLimit = 10_000_000
    IssueNFTGasLimit = 60_000_000
    DeployNFTTemplateGasLimit = 20_000_000
    ChangeOwnerGasLimit = 20_000_000
    SetSpecialRolesGasLimit = 60_000_000
    IssueTokenEGLDCost = "0.05"
    DeployNFTTemplateEGLDCost = "0"
    WithdrawFromMinterGasLimit = 10_000_000
    RequestWithdrawThroughMinterGasLimit = 50_000_000
    NoFeeOnMintContracts = [
        "erd1qqqqqqqqqqqqqpgqwt37h7vgwkfgql68nhfvx4l7ncpzmyndt3xqru6kf6"
    ]

[Database]
    Dialect = "postgres"
    Host = "localhost"
    # ConnectionName= "youbei-339521:us-central1:youbei-dev"
    Port = 5432
    DbName = "youbei-api"
    User = "youbei"
    Password = "youbei"#"-JVx`g,m$tz;T9{c^s&Q%Zs>i7dGt}O)"
    SslMode = "disable"
    MaxOpenConns = 50
    MaxIdleConns = 10
    ShouldMigrate = true

[Auth]
    JwtSecret = "jwtSecret"
    JwtIssuer = "localhost:5000"
    JwtKeySeedHex = "d6592724167553acf9c8cba9a7dbc7f514efc757d7906546cecfdfc5d4c2e8d1"
    JwtExpiryMins = 1440

[Cache]
    Url = "redis://localhost:6379"

[Swagger]
    LocalDocRoute = "http://localhost:5000/swagger/doc.json"
    Enabled = true

[Bot]
    Token = "bot_token"
    RecID = "recipient_id"
    Enable = false

[Monitor]
    ObserverMonitorEnable = false

[CDN]
    Name = "youbei"
    ApiKey = "299768791129295"
    ApiSecret = "fIFsn9UK3_BMSe4qOIAzqQ3eoZY"
    #Selector = "cloudy"
    Selector = "local"
    BaseUrl = "http://localhost:5000/image/"
    RootDir = "/home/ubuntu/pics"