[ConnectorApi]
    Port = "5000"

    Username = ""

    Password = ""

    Addresses = [
        "erd1qqqqqqqqqqqqqpgqxrtj3jrrztan0c5ckhd3crs9w997s6ynt9usacn2n0",
    ]

    Identifiers = [
        "collection_register",
        "put_nft_for_sale",
        "buy_nft",
        "withdraw_nft",
    ]

[Blockchain]
    ChainID = "D"
    GasPrice = 1_000_000_000
    PemPath = "./config/owner.pem"
    ProxyUrl = "https://devnet-gateway.elrond.com"

[Database]
    Dialect = "postgres"
    Host = "localhost"
    Port = 5432
    DbName = "erdsea_db"
    User = "postgres"
    Password = "root"
    SslMode = "disable"
    MaxOpenConns = 50
    MaxIdleConns = 10
    ShouldMigrate = true
