[ConnectorApi]
    Address = "localhost:5000"
    Username = ""
    Password = ""
    Addresses = [
        "erd1qqqqqqqqqqqqqpgqm4dmwyxc5fsj49z3jcu9h08azjrcf60kt9uspxs483",
    ]
    Identifiers = [
        "putNftForSale",
        "buyNft",
        "withdrawNft",
        "makeOffer",
        "acceptOffer",
        "cancelOffer",
        "startAuction",
        "placeBid",
        "endAuction",
        "deposit",
        "withdraw",
    ]

[Blockchain]
    ChainID = "D"
    GasPrice = 1_000_000_000
    PemPath = "./config/owner.pem"
    ProxyUrl = "https://devnet-gateway.elrond.com"
    MarketplaceAddress = "erd1qqqqqqqqqqqqqpgqm4dmwyxc5fsj49z3jcu9h08azjrcf60kt9uspxs483"
    DeployerAddress = "erd1qqqqqqqqqqqqqpgqupgxrdhphusx5crgvg454u9k4zqsp5mst9usqlrfyy"
    SystemSCAddress = "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u"
    ListNftGasLimit = 20_000_000
    BuyNftGasLimit = 15_000_000
    WithdrawNftGasLimit = 15_000_000
    MintTokenGasLimit = 10_000_000
    MakeOfferGasLimit = 20_000_000
    AcceptOfferGasLimit = 20_000_000
    CancelOfferGasLimit = 20_000_000
    StartAuctionGasLimit = 20_000_000
    PlaceBidGasLimit = 20_000_000
    EndAuctionGasLimit = 20_000_000
    DepositGasLimit = 10_000_000
    WithdrawGasLimit = 10_000_000
    WithdrawCreatorRoyaltiesGasLimit = 10_000_000
    IssueNFTGasLimit = 60_000_000
    DeployNFTTemplateGasLimit = 20_000_000
    ChangeOwnerGasLimit = 20_000_000
    SetSpecialRolesGasLimit = 60_000_000
    IssueTokenEGLDCost = "0.05"
    DeployNFTTemplateEGLDCost = "0"
    WithdrawFromMinterGasLimit = 10_000_000
    RequestWithdrawThroughMinterGasLimit = 50_000_000

[Database]
    Dialect = "postgres"
    Host = "localhost"
    Port = 5432
    DbName = "erdsea_db"
    User = "postgres"
    Password = "root"
    SslMode = "disable"
    MaxOpenConns = 50
    MaxIdleConns = 10
    ShouldMigrate = true

[Auth]
    JwtSecret = "jwtSecret"
    JwtIssuer = "localhost:5000"
    JwtKeySeedHex = "d6592724167553acf9c8cba9a7dbc7f514efc757d7906546cecfdfc5d4c2e8d1"
    JwtExpiryMins = 120

[Cache]
    Url = "redis://localhost:6379"

[Swagger]
    LocalDocRoute = "http://localhost:5000/swagger/doc.json"
    Enabled = true

[Bot]
    Token = "bot_token"
    RecID = "recipient_id"
    Enable = false

[Monitor]
    ObserverMonitorEnable = false

[CDN]
    Name = "cloud_name"
    ApiKey = "cdn_api_key"
    ApiSecret = "cdn_api_secret"
