[ConnectorApi]
    Address = "localhost:5000"
    Username = ""
    Password = ""
    Addresses = [
        "erd1qqqqqqqqqqqqqpgqj8vnqw76wq333qwx2wjf2nyn89dc8jhct9usvxzd7g",
    ]
    Identifiers = [
        "putNftForSale",
        "buyNft",
        "withdrawNft",
    ]

[Blockchain]
    ChainID = "D"
    GasPrice = 1_000_000_000
    PemPath = "./config/owner.pem"
    ProxyUrl = "https://devnet-gateway.elrond.com"
    MarketplaceAddress = "erd1qqqqqqqqqqqqqpgqj8vnqw76wq333qwx2wjf2nyn89dc8jhct9usvxzd7g"
    ListNftGasLimit = 20_000_000
    BuyNftGasLimit = 15_000_000
    WithdrawNftGasLimit = 15_000_000
    MintTokenGasLimit = 10_000_000

[Database]
    Dialect = "postgres"
    Host = "localhost"
    Port = 5432
    DbName = "erdsea_db"
    User = "postgres"
    Password = "root"
    SslMode = "disable"
    MaxOpenConns = 50
    MaxIdleConns = 10
    ShouldMigrate = true

[Auth]
    JwtSecret = "jwtSecret"
    JwtIssuer = "localhost:5000"
    JwtKeySeedHex = "d6592724167553acf9c8cba9a7dbc7f514efc757d7906546cecfdfc5d4c2e8d1"
    JwtExpiryMins = 120

[Cache]
    Url = "redis://localhost:6379"

[Swagger]
    LocalDocRoute = "http://localhost:5000/swagger/doc.json"
    Enabled = true

[Bot]
    Token = "bot_token"
    RecID = "recipient_id"
    Enable = false

[Monitor]
    ObserverMonitorEnable = false

[CDN]
    Name = "cloud_name"
    ApiKey = "cdn_api_key"
    ApiSecret = "cdn_api_secret"
