definitions:
  data.ApiResponse:
    properties:
      data: {}
      error:
        type: string
    type: object
  handlers.createTokenRequest:
    properties:
      address:
        type: string
      message:
        type: string
      signature:
        type: string
    type: object
  handlers.tokenPayload:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: erdsea-api
  version: "1.0"
paths:
  /auth/access:
    post:
      consumes:
      - application/json
      description: creates an access token
      parameters:
      - description: token creation request
        in: body
        name: tokenRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.createTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.tokenPayload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/data.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/data.ApiResponse'
      summary: access token
swagger: "2.0"
