on:
  push:
    branches:
      - main
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: youbei-api
  SERVICE: youbei-api
  PROJECT_ID: asvsfs
  REGISTRY_HOSTNAME: ghcr.io
  HTTP_PORT: 5050
  HTTP_PORT_EXPOSE: 5070
  GOPRIVATE: "https://github.com/ENFT-DAO"
  REPO_TOKEN: ${{ secrets.REPO_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
jobs:
  deploy:
    runs-on: prod
    name: deploy
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          export HOME=/home/amir
          echo $PAT_TOKEN | docker login ghcr.io -u asvsfs --password-stdin
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker system prune -f
          docker build -t "$PROJECT_ID"/"$IMAGE":"$TAG"  \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_TOKEN="$GITHUB_TOKEN" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          echo $PAT_TOKEN | docker login ghcr.io -u asvsfs --password-stdin
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG"
          docker rmi -f $IMAGE:latest
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG" $IMAGE:latest
      - name: Deploy
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker run -p 5050:5050 --name youbei-api "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG"
  
      