on:
  push:
    branches:
      - main
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: youbei-api
  SERVICE: youbei-api
  PROJECT_ID: asvsfs
  REGISTRY_HOSTNAME: ghcr.io
  HTTP_PORT: 5050
  HTTP_PORT_EXPOSE: 5070
  GOPRIVATE: "https://github.com/ENFT-DAO"
  REPO_TOKEN: ${{ secrets.REPO_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
jobs:
  deploy:
    runs-on: prod
    name: deploy
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          export HOME=/home/amir
          echo $PAT_TOKEN | docker login ghcr.io -u asvsfs --password-stdin
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker system prune -f
          docker build -t "$PROJECT_ID"/"$IMAGE":"$TAG"  \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_TOKEN="$GITHUB_TOKEN" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
          docker tag "$PROJECT_ID"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG"

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          echo $PAT_TOKEN | docker login ghcr.io -u asvsfs --password-stdin
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG"
          docker rmi -f $IMAGE:latest
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG" $IMAGE:latest
      - name: Deploy
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker stop $SERVICE
          docker rm $SERVICE
          docker run -d -p 5000:5000 --name youbei-api --network prod_net -v /srv/youbei-api/pics:/srv/youbei-api/pics -v /srv/youbei/cache:/tmp -v /srv/configs/youbei/prod-youbei-api-config.toml:/config/prod-youbei-api-config.toml "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG" ./youbei-api --general-config /config/prod-youbei-api-config.toml
  
      